module.exports = {
  // rule sets: official
  'no-plusplus': ['off'],
  'func-names': ['off'],
  'no-await-in-loop': ['off'],
  'generator-star-spacing': 0,
  'function-paren-newline': 0,
  'sort-imports': 0,
  'class-methods-use-this': 0,
  'no-confusing-arrow': 0,
  'linebreak-style': 0,
  'no-prototype-builtins': 'off',
  'no-undef': 0,
  'brace-style': 0,
  'comma-dangle': 0,
  'comma-spacing': 'off',
  'default-param-last': 'off',
  'dot-notation': 1,
  'func-call-spacing': 'off',
  indent: 'off',
  'init-declarations': 'off',
  'keyword-spacing': 'off',
  'lines-between-class-members': 'off',
  'no-array-constructor': 'off',
  'no-dupe-class-members': 'off',
  'no-duplicate-imports': 'off',
  'no-empty-function': 'off',
  'no-extra-parens': 'off',
  'no-extra-semi': 'off',
  'no-implied-eval': 'off',
  'no-invalid-this': 'error',
  'no-loop-func': 'error',
  'no-loss-of-precision': 'off',
  'no-magic-numbers': 'off',
  'no-redeclare': 'error',
  'no-shadow': [
    'warn',
    {
      allow: ['done', 'resolve', 'reject', 'cb', 'callback']
    }
  ],
  'no-throw-literal': 'error',
  'no-unused-expressions': 'error',
  'no-unused-vars': [
    'warn',
    {
      argsIgnorePattern: '^_'
    }
  ],
  'no-use-before-define': 'off',
  'no-useless-constructor': 'error',
  quotes: 'off',
  'require-await': 'off',
  'no-return-await': 'off',
  semi: 'off',
  'space-infix-ops': 'off',
  camelcase: 0,
  // Conflict with prettier
  'arrow-body-style': 0,
  'arrow-parens': 0,
  'object-curly-newline': 0,
  'implicit-arrow-linebreak': 0,
  'operator-linebreak': 0,
  'no-param-reassign': 0,
  'no-continue': 0,
  'no-case-declarations': 'off',
  'global-require': 'off',
  'space-before-function-paren': 0,
  // rule sets: eslint-plugin-import
  'import/no-unresolved': 0,
  'import/named': 0,
  'import/order': 0,
  'import/no-named-as-default': 0,
  'import/no-cycle': 0,
  'import/prefer-default-export': 0,
  'import/no-default-export': 0,
  'import/no-extraneous-dependencies': 0,
  'import/no-named-as-default-member': 0,
  'import/no-duplicates': 0,
  'import/no-self-import': 0,
  'import/extensions': 0,
  'import/no-useless-path-segments': 0,
  // rule sets: eslint-plugin-eslin-comments
  'eslint-comments/no-unlimited-disable': 0
};
